spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        message_in:
          destination: test
          contentType: application/json
        message_out:
          destination: test
          contentType: application/json